name: Proxy Check

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  proxy_check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Scraping Proxy From Internet
      run: python3 proxy_scraper.py

    - name: Removing Duplicate Proxy
      run: cat http_proxies.txt | sort -u > proxies.txt

    - name: Set timezone to IST
      run: export TZ='Asia/Kolkata'

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add proxies.txt
        git commit -m "Update Proxy List: $(date)"
        git push
